# Generated by Django 6.0.3 on 2026-04-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0011_subject_exam_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_platform', models.CharField(default='youtube', max_length=50)),
                ('video_platform', models.CharField(default='youtube', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
